import test from 'node:test';
import assert from 'node:assert/strict';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync} from 'node:fs';
import worker,{validateOrder} from '../server/worker.mjs';
function setup(){const sqlite=new DatabaseSync(':memory:');sqlite.exec(readFileSync(new URL('../server/schema.sql',import.meta.url),'utf8'));return {DB:{prepare(sql){return {bind(...args){return {async first(){return sqlite.prepare(sql).get(...args)??null;},async run(){return sqlite.prepare(sql).run(...args);}};},async all(){return {results:sqlite.prepare(sql).all()};}};}},sqlite,ORDERS_ENABLED:'true',RATE_LIMIT_SECRET:'test-only-not-production'};}
const order={name:'Test Parent',phone:'01000000000',city:'Test City',address:'Test address 123',governorate:'DK',quantity:2,payment:'instapay',consent:true,notes:'',website:''};
const req=(body=order,options={})=>new Request('https://rvu-kids.company/api/orders',{method:'POST',headers:{Origin:'https://rvu-kids.company','Content-Type':'application/json','Idempotency-Key':'8a606ae1-0ab7-4553-a375-a57a38c216b1','CF-Connecting-IP':'192.0.2.1',...options},body:JSON.stringify(body)});
test('validation rejects invalid quantity, phone, region and missing consent',()=>{for(const patch of [{quantity:-1},{quantity:1.5},{quantity:21},{phone:'abc'},{governorate:'unknown'},{consent:false},{name:'x'},{website:'bot'}])assert.equal(validateOrder({...order,...patch}),null);});
test('offline by default and no public order reads',async()=>{assert.equal((await worker.fetch(req(),{})).status,503);assert.equal((await worker.fetch(new Request('https://rvu-kids.company/api/orders'),{})).status,405);});
test('unknown shipping stays null and client price/status are ignored',async()=>{const env=setup();const response=await worker.fetch(req({...order,total:1,status:'paid_verified'}),env);assert.equal(response.status,201);const result=await response.json();assert.equal(result.status,'pending_review');assert.deepEqual(Object.keys(result).sort(),['reference','status']);const saved=env.sqlite.prepare('SELECT * FROM orders').get();assert.equal(saved.subtotal_egp,400);assert.equal(saved.shipping_egp,null);assert.equal(saved.total_egp,null);assert.equal(saved.status,'pending_review');});
test('verified shipping is calculated on the server',async()=>{const env=setup();env.sqlite.prepare('INSERT INTO shipping_rates VALUES (?,?,1,?)').run('DK',73,'test-fixture-only');const response=await worker.fetch(req(),env);assert.equal(response.status,201);assert.equal(env.sqlite.prepare('SELECT total_egp FROM orders').get().total_egp,473);});
test('retries never create a second order and changed payload conflicts',async()=>{const env=setup();const a=await (await worker.fetch(req(),env)).json();const b=await (await worker.fetch(req(),env)).json();assert.equal(a.reference,b.reference);assert.equal(env.sqlite.prepare('SELECT count(*) AS count FROM orders').get().count,1);assert.equal((await worker.fetch(req({...order,quantity:3}),env)).status,409);});
test('cross origin requests rejected and database failure cannot report success',async()=>{assert.equal((await worker.fetch(req(order,{Origin:'https://other.example'}),setup())).status,403);const env=setup();env.DB.prepare=()=>{throw Error('database offline');};assert.equal((await worker.fetch(req(),env)).status,503);});
test('payment states require a recorded manual verification',async()=>{const env=setup();await worker.fetch(req(),env);assert.throws(()=>env.sqlite.exec("UPDATE orders SET status='paid_verified'"));});
test('abuse limit rejects the ninth unique request in the same hour',async()=>{const env=setup();for(let i=0;i<8;i++)assert.equal((await worker.fetch(req(order,{'Idempotency-Key':crypto.randomUUID()}),env)).status,201);assert.equal((await worker.fetch(req(order,{'Idempotency-Key':crypto.randomUUID()}),env)).status,429);});
